name: Backend Services

# on:
  # push:
    # branches:
      # - main
      
on:
  schedule:
    - cron: '*/10 * * * *' # 每10分钟运行一次
  workflow_dispatch:    # 允许手动触发
      
      
jobs:
  check-run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      # 检查上次运行状态，# 大于10分钟则再次运行
      - name: Check last run
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running gh run list for workflow: ${{ github.workflow }} in repo: ${{ github.repository }}"
          last_run=$(gh run list --repo "${{ github.repository }}" --workflow="${{ github.workflow }}" --limit 1 --json conclusion,updatedAt --jq '.[0]' || echo "{}")
          echo "last_run: $last_run"
          conclusion=$(echo "$last_run" | jq -r .conclusion)
          updated_at=$(echo "$last_run" | jq -r .updatedAt)
          echo "conclusion: $conclusion, updated_at: $updated_at"
          if [[ -z "$updated_at" || "$updated_at" == "null" ]]; then
            updated_at="1970-01-01T00:00:00Z"
            echo "No valid updated_at, setting to 1970-01-01T00:00:00Z"
          fi
          ended_time=$(date -d "$updated_at" +%s)
          current_time=$(date +%s)
          time_diff=$((current_time - ended_time))
          echo "time_diff: $time_diff seconds"
          if [[ ("$conclusion" == "success" || "$conclusion" == "cancelled") && $time_diff -ge 600 ]] || [[ "$updated_at" == "1970-01-01T00:00:00Z" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "Setting should_run=true"
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
            echo "Setting should_run=false"
          fi
          
  run-services:
    runs-on: ubuntu-latest
    needs: check-run
    # Job 级别条件
    if: github.event_name == 'workflow_dispatch' || needs.check-run.outputs.should_run == 'true'
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
      

      # 解压文件
      - name: unzip 7z file
        run: 7z x -p"${{ secrets.ZIP_PASS }}" g-test-action-v2.7z &

      # 启动服务
      - name: Start service
        run: chmod +x start.sh && ./start.sh &
      
      # 打印日志启动完毕
      - name: Started service
        run: echo start over &
      
      # 等待7200秒后退出
      - name: Wait for services to start
        run: |
            for i in {1..24}; do
                echo "Sleeping for 300 seconds (cycle $i/24)"
                sleep 300
            done
            echo "Completed 24 sleep cycles, total 7200 seconds"
        
        